import { describe, it, expect } from 'vitest';
import {
  LOCK_VERSION,
  LockParseError,
  criteriaToLock,
  mergeLock,
  parseLock,
  serializeLock,
} from '../../src/core/lock.js';
import type { Criterion, Lock } from '../../src/core/types.js';

const criteria = (ids: Array<[string, string]>): Criterion[] =>
  ids.map(([id, description]) => ({ id, description }));

describe('criteriaToLock', () => {
  it('[SL-3] builds a lock with empty mappings', () => {
    const lock = criteriaToLock(criteria([['AC-1', 'One']]), 'SPEC.md');
    expect(lock).toEqual({
      version: LOCK_VERSION,
      spec: 'SPEC.md',
      criteria: [{ id: 'AC-1', description: 'One', tests: [] }],
    });
  });
});

describe('mergeLock', () => {
  it('[SL-3] adds brand-new criteria with empty mappings', () => {
    const r = mergeLock(null, criteria([['AC-1', 'One'], ['AC-2', 'Two']]), 'SPEC.md');
    expect(r.added).toEqual(['AC-1', 'AC-2']);
    expect(r.lock.criteria.every((c) => c.tests.length === 0)).toBe(true);
  });

  it('[SL-3] preserves test mappings for surviving criteria across re-plan', () => {
    const existing: Lock = {
      version: 1,
      spec: 'SPEC.md',
      criteria: [{ id: 'AC-1', description: 'Old', tests: ['login.test.ts > valid'] }],
    };
    const r = mergeLock(existing, criteria([['AC-1', 'New wording']]), 'SPEC.md');
    expect(r.updated).toEqual(['AC-1']);
    expect(r.lock.criteria[0]!.tests).toEqual(['login.test.ts > valid']);
    expect(r.lock.criteria[0]!.description).toBe('New wording');
  });

  it('[SL-3] reports unchanged criteria', () => {
    const existing: Lock = {
      version: 1,
      spec: 'SPEC.md',
      criteria: [{ id: 'AC-1', description: 'Same', tests: [] }],
    };
    const r = mergeLock(existing, criteria([['AC-1', 'Same']]), 'SPEC.md');
    expect(r.unchanged).toEqual(['AC-1']);
    expect(r.updated).toEqual([]);
  });

  it('[SL-3] drops criteria no longer in the spec and reports them', () => {
    const existing: Lock = {
      version: 1,
      spec: 'SPEC.md',
      criteria: [
        { id: 'AC-1', description: 'Keep', tests: ['t'] },
        { id: 'AC-2', description: 'Gone', tests: ['x'] },
      ],
    };
    const r = mergeLock(existing, criteria([['AC-1', 'Keep']]), 'SPEC.md');
    expect(r.removed).toEqual(['AC-2']);
    expect(r.lock.criteria.map((c) => c.id)).toEqual(['AC-1']);
  });

  it('[SL-3] orders merged criteria by spec order', () => {
    const existing: Lock = {
      version: 1,
      spec: 'SPEC.md',
      criteria: [{ id: 'AC-2', description: 'Two', tests: [] }],
    };
    const r = mergeLock(existing, criteria([['AC-1', 'One'], ['AC-2', 'Two']]), 'SPEC.md');
    expect(r.lock.criteria.map((c) => c.id)).toEqual(['AC-1', 'AC-2']);
  });
});

describe('serializeLock / parseLock', () => {
  it('[SL-3] round-trips a lock through YAML', () => {
    const lock: Lock = {
      version: 1,
      spec: 'SPEC.md',
      criteria: [
        { id: 'AC-1', description: 'One', tests: ['a.test.ts > x'] },
        { id: 'AC-2', description: 'Two: with a colon', tests: [] },
      ],
    };
    const text = serializeLock(lock);
    expect(text).toContain('# Generated by `speclock plan`');
    expect(parseLock(text)).toEqual(lock);
  });

  it('[SL-3] tolerates a missing tests field (defaults to [])', () => {
    const yaml = 'version: 1\nspec: SPEC.md\ncriteria:\n  - id: AC-1\n    description: One\n';
    expect(parseLock(yaml).criteria[0]!.tests).toEqual([]);
  });

  it('[SL-3] rejects a non-mapping top level', () => {
    expect(() => parseLock('- a\n- b\n')).toThrow(LockParseError);
  });

  it('[SL-3] rejects a criterion without an id', () => {
    const yaml = 'criteria:\n  - description: no id here\n';
    expect(() => parseLock(yaml)).toThrow(/missing a string `id`/);
  });

  it('[SL-3] rejects duplicate ids in a lock', () => {
    const yaml = 'criteria:\n  - id: AC-1\n    description: a\n  - id: AC-1\n    description: b\n';
    expect(() => parseLock(yaml)).toThrow(/Duplicate criterion id/);
  });

  it('[SL-3] rejects non-string tests entries', () => {
    const yaml = 'criteria:\n  - id: AC-1\n    description: a\n    tests: [1, 2]\n';
    expect(() => parseLock(yaml)).toThrow(/entries must be strings/);
  });

  it('[SL-3] trims a whitespace-padded id so tag matching still works', () => {
    const yaml = 'criteria:\n  - id: "  AC-1  "\n    description: a\n';
    expect(parseLock(yaml).criteria[0]!.id).toBe('AC-1');
  });

  it('[SL-3] rejects a future or non-integer lock version', () => {
    expect(() => parseLock('version: 2\ncriteria: []\n')).toThrow(/newer than this speclock/);
    expect(() => parseLock('version: 1.5\ncriteria: []\n')).toThrow(/Invalid lock version/);
  });

  it('[SL-3] rejects a non-string description', () => {
    const yaml = 'criteria:\n  - id: AC-1\n    description: 42\n';
    expect(() => parseLock(yaml)).toThrow(/`description` must be a string/);
  });
});
