/**
 * Lock file (specs/*.yaml) model — pure.
 *
 * The lock records the acceptance criteria and their test mappings. It is the
 * artifact reviewers look at in a PR, so it is plain, comment-headed YAML.
 */

import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { Criterion, Lock, LockCriterion } from './types.js';

export const LOCK_VERSION = 1;

/** Thrown when a lock file is not shaped like a lock. */
export class LockParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'LockParseError';
  }
}

const HEADER = `# Generated by \`speclock plan\` from the spec below. Re-running plan is safe:
# it preserves the \`tests:\` you add and only syncs ids/descriptions from the spec.
#
# A criterion is covered by any test whose name contains its id in brackets,
# e.g. [AC-1]. You can also list explicit test-name substrings under \`tests:\`.
`;

/** Build a fresh lock from parsed criteria (all mappings empty). */
export function criteriaToLock(criteria: Criterion[], specPath: string): Lock {
  return {
    version: LOCK_VERSION,
    spec: specPath,
    criteria: criteria.map((c) => ({ id: c.id, description: c.description, tests: [] })),
  };
}

export interface MergeResult {
  lock: Lock;
  added: string[];
  updated: string[];
  unchanged: string[];
  removed: string[];
}

/**
 * Sync fresh criteria (from a SPEC) into an existing lock.
 *
 * - Surviving criteria keep their `tests` mapping; descriptions are refreshed.
 * - New criteria are appended with an empty mapping.
 * - Criteria no longer in the spec are dropped (and reported as `removed`).
 *
 * The new lock's criteria order follows the spec.
 */
export function mergeLock(
  existing: Lock | null,
  criteria: Criterion[],
  specPath: string,
): MergeResult {
  const prev = new Map<string, LockCriterion>();
  for (const c of existing?.criteria ?? []) prev.set(c.id, c);

  const added: string[] = [];
  const updated: string[] = [];
  const unchanged: string[] = [];

  const merged: LockCriterion[] = criteria.map((c) => {
    const old = prev.get(c.id);
    if (!old) {
      added.push(c.id);
      return { id: c.id, description: c.description, tests: [] };
    }
    if (old.description !== c.description) updated.push(c.id);
    else unchanged.push(c.id);
    return { id: c.id, description: c.description, tests: [...old.tests] };
  });

  const freshIds = new Set(criteria.map((c) => c.id));
  const removed = [...prev.keys()].filter((id) => !freshIds.has(id));

  return {
    lock: { version: LOCK_VERSION, spec: specPath, criteria: merged },
    added,
    updated,
    unchanged,
    removed,
  };
}

/** Serialize a lock to YAML with an explanatory header comment. */
export function serializeLock(lock: Lock): string {
  const body = stringifyYaml(
    {
      version: lock.version,
      spec: lock.spec,
      criteria: lock.criteria.map((c) => ({
        id: c.id,
        description: c.description,
        tests: c.tests,
      })),
    },
    { lineWidth: 0 },
  );
  return `${HEADER}${body}`;
}

function asStringArray(value: unknown): string[] {
  if (value == null) return [];
  if (!Array.isArray(value)) {
    throw new LockParseError('`tests` must be a list of strings.');
  }
  return value.map((v) => {
    if (typeof v !== 'string') {
      throw new LockParseError('`tests` entries must be strings.');
    }
    return v;
  });
}

/** Parse and validate a lock from YAML text. */
export function parseLock(text: string): Lock {
  let raw: unknown;
  try {
    raw = parseYaml(text);
  } catch (e) {
    throw new LockParseError(
      `Invalid YAML: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
  if (raw == null || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new LockParseError('Expected a YAML mapping at the top level.');
  }
  const obj = raw as Record<string, unknown>;

  let version = LOCK_VERSION;
  if (obj.version != null) {
    if (typeof obj.version !== 'number' || !Number.isInteger(obj.version) || obj.version < 1) {
      throw new LockParseError(`Invalid lock version: ${String(obj.version)} (expected a positive integer).`);
    }
    if (obj.version > LOCK_VERSION) {
      throw new LockParseError(
        `Lock version ${obj.version} is newer than this speclock supports (${LOCK_VERSION}). Upgrade speclock.`,
      );
    }
    version = obj.version;
  }
  const spec = typeof obj.spec === 'string' ? obj.spec : '';

  if (obj.criteria != null && !Array.isArray(obj.criteria)) {
    throw new LockParseError('`criteria` must be a list.');
  }
  const rawCriteria = (obj.criteria as unknown[]) ?? [];

  const seen = new Set<string>();
  const criteria: LockCriterion[] = rawCriteria.map((item, i) => {
    if (item == null || typeof item !== 'object' || Array.isArray(item)) {
      throw new LockParseError(`criteria[${i}] must be a mapping.`);
    }
    const c = item as Record<string, unknown>;
    const id = typeof c.id === 'string' ? c.id.trim() : '';
    if (id === '') {
      throw new LockParseError(`criteria[${i}] is missing a string \`id\`.`);
    }
    if (seen.has(id)) {
      throw new LockParseError(`Duplicate criterion id "${id}" in lock.`);
    }
    seen.add(id);
    if (c.description != null && typeof c.description !== 'string') {
      throw new LockParseError(`criteria[${i}] \`description\` must be a string.`);
    }
    const description = typeof c.description === 'string' ? c.description : '';
    return { id, description, tests: asStringArray(c.tests) };
  });

  return { version, spec, criteria };
}
